-- ==========================================
-- KBO Feed 최종 데이터베이스 설정 (완성판 - Ads, Follows, 인증, 트리거 포함)
-- ==========================================

-- 1. 테이블 초기화
-- ------------------------------------------

-- profiles 테이블
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    display_name TEXT,
    avatar_url TEXT,
    bio TEXT,
    favorite_team TEXT,
    is_verified BOOLEAN DEFAULT FALSE,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- posts 테이블
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    content TEXT,
    image_url TEXT,
    team_tag TEXT,
    retweet_id BIGINT REFERENCES public.posts(id) ON DELETE SET NULL,
    likes_count INT DEFAULT 0,
    retweets_count INT DEFAULT 0,
    comments_count INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- likes 테이블
CREATE TABLE IF NOT EXISTS public.likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, post_id)
);

-- retweets 테이블
CREATE TABLE IF NOT EXISTS public.retweets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, post_id)
);

-- comments 테이블
CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- follows 테이블
CREATE TABLE IF NOT EXISTS public.follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    following_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(follower_id, following_id)
);

-- ads 테이블
CREATE TABLE IF NOT EXISTS public.ads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    image_url TEXT,
    link_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- notifications 테이블
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    sender_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    type TEXT NOT NULL,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- 2. 보안 정책 (RLS) 설정
-- ==========================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.retweets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Select
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Posts are viewable by everyone" ON posts FOR SELECT USING (true);
CREATE POLICY "Likes are viewable by everyone" ON likes FOR SELECT USING (true);
CREATE POLICY "Retweets are viewable by everyone" ON retweets FOR SELECT USING (true);
CREATE POLICY "Comments are viewable by everyone" ON comments FOR SELECT USING (true);
CREATE POLICY "Follows are viewable by everyone" ON follows FOR SELECT USING (true);
CREATE POLICY "Ads are viewable by everyone" ON ads FOR SELECT USING (true);
CREATE POLICY "Notifications are viewable by owner" ON notifications FOR SELECT USING (auth.uid() = receiver_id);

-- Manage
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own posts" ON posts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own posts" ON posts FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own posts" ON posts FOR DELETE USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own likes" ON likes FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own retweets" ON retweets FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own comments" ON comments FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own follows" ON follows FOR ALL USING (auth.uid() = follower_id);

-- Admin
CREATE POLICY "Admins can manage ads" ON ads FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (is_admin = true OR id = '97de821b-da04-4e27-9bce-b9705b33c8cd'::uuid))
);

-- ==========================================
-- 3. 함수 및 트리거
-- ==========================================

-- 회원가입 시 프로필 자동 생성
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, display_name, avatar_url, favorite_team, is_admin)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'username', 'user_' || substr(new.id::text, 1, 8)),
    COALESCE(new.raw_user_meta_data->>'display_name', '새로운 탐험가'),
    new.raw_user_meta_data->>'avatar_url',
    new.raw_user_meta_data->>'favorite_team',
    (new.id = '97de821b-da04-4e27-9bce-b9705b33c8cd'::uuid)
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 좋아요 토글 & 알림
CREATE OR REPLACE FUNCTION public.toggle_like(post_id_input BIGINT, user_id_input UUID)
RETURNS INT AS $$
DECLARE
    exists_id BIGINT;
    new_count INT;
    target_owner_id UUID;
BEGIN
    SELECT id INTO exists_id FROM public.likes WHERE post_id = post_id_input AND user_id = user_id_input;
    SELECT user_id INTO target_owner_id FROM public.posts WHERE id = post_id_input;
    IF exists_id IS NOT NULL THEN
        DELETE FROM public.likes WHERE id = exists_id;
        UPDATE public.posts SET likes_count = GREATEST(0, likes_count - 1) WHERE id = post_id_input RETURNING likes_count INTO new_count;
    ELSE
        INSERT INTO public.likes (post_id, user_id) VALUES (post_id_input, user_id_input);
        UPDATE public.posts SET likes_count = likes_count + 1 WHERE id = post_id_input RETURNING likes_count INTO new_count;
        IF user_id_input != target_owner_id THEN
            INSERT INTO public.notifications (receiver_id, sender_id, type, post_id) VALUES (target_owner_id, user_id_input, 'like', post_id_input);
        END IF;
    END IF;
    RETURN new_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 리트윗 토글 & 알림
CREATE OR REPLACE FUNCTION public.toggle_retweet(post_id_input BIGINT, user_id_input UUID)
RETURNS INT AS $$
DECLARE
    exists_id BIGINT;
    new_count INT;
    target_owner_id UUID;
BEGIN
    SELECT id INTO exists_id FROM public.retweets WHERE post_id = post_id_input AND user_id = user_id_input;
    SELECT user_id INTO target_owner_id FROM public.posts WHERE id = post_id_input;
    IF exists_id IS NOT NULL THEN
        DELETE FROM public.retweets WHERE id = exists_id;
        DELETE FROM public.posts WHERE user_id = user_id_input AND retweet_id = post_id_input;
        UPDATE public.posts SET retweets_count = GREATEST(0, retweets_count - 1) WHERE id = post_id_input RETURNING retweets_count INTO new_count;
    ELSE
        INSERT INTO public.retweets (post_id, user_id) VALUES (post_id_input, user_id_input);
        INSERT INTO public.posts (user_id, retweet_id, content) VALUES (user_id_input, post_id_input, NULL);
        UPDATE public.posts SET retweets_count = retweets_count + 1 WHERE id = post_id_input RETURNING retweets_count INTO new_count;
        IF user_id_input != target_owner_id THEN
            INSERT INTO public.notifications (receiver_id, sender_id, type, post_id) VALUES (target_owner_id, user_id_input, 'retweet', post_id_input);
        END IF;
    END IF;
    RETURN new_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 댓글 수 자동 업데이트
CREATE OR REPLACE FUNCTION public.handle_comment_count()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.posts SET comments_count = comments_count + 1 WHERE id = NEW.post_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.posts SET comments_count = GREATEST(0, comments_count - 1) WHERE id = OLD.post_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_comment_created ON public.comments;
CREATE TRIGGER on_comment_created AFTER INSERT OR DELETE ON public.comments FOR EACH ROW EXECUTE FUNCTION public.handle_comment_count();
